fragment webformElementType on WebformElementType {
  id
  type
}

fragment webformElement on WebformElement {
  __typename
  ...webformElementType
}

fragment webform on Webform {
  title
  elements {
    ...webformElement
  }
}

query webform($webform_id: String!) {
  form: webformById(webform_id: $webform_id) {
    ...webform
  }
}
